<?php
// src/Acme/TaskBundle/Repository/UserRepository.php
namespace Acme\TaskBundle\Repository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

}