# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_db_provider:
            entity:
                class: AcmeTaskBundle:User
                property: userame
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        dev_secured_area:
            pattern: ^/
            anonymous: ~
            # http_basic: ~
            provider: user_db_provider
            # form_login:
            #    login_path: login
            #    check_path: login_check
        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    encoders:
        Acme\TaskBundle\Entity\User:
            algorithm: bcrypt
